name: settheory_local_db
volumes:
  SetTheory-db-data:

services:
  settheory_db:
    image: postgres:17.5-alpine3.21
    networks:
      - settheory_local_network
    hostname: settheory-db-local
    volumes:
      - SetTheory-db-data:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_PASSWORD: setTheoryLocal123! ## ONLY FOR LOCAL DEVELOPMENT

  settheory_adminer:
    image: adminer
    depends_on:
      settheory_db:
        condition: service_healthy
        restart: true
    networks:
      - settheory_local_network
    hostname: settheory-adminer-local
    ports:
      - 8942:8080
networks:
  settheory_local_network:
    name: settheory_local_network
    external: true
