name: settheory_local_db
volumes:
  SetTheory-db-data:
  SetTheory-pgadmin-data:

services:
  settheory_db:
    image: postgres:17.5-alpine3.21
    networks:
      - settheory_local_network
    hostname: settheory-db-local
    volumes:
      - SetTheory-db-data:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_PASSWORD: setTheoryLocal123! ## ONLY FOR LOCAL DEVELOPMENT

  settheory_pgadmin:
    image: dpage/pgadmin4
    depends_on:
      settheory_db:
        condition: service_healthy
        restart: true
    networks:
      - settheory_local_network
    hostname: settheory-pgadmin-local
    ports:
      - 8942:80
    environment:
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4-servers/servers.json
      - PGADMIN_DISABLE_POSTFIX=1
      - PGADMIN_DEFAULT_EMAIL=settheory@local.dev
      - PGADMIN_DEFAULT_PASSWORD=setTheoryLocal123! ## ONLY FOR LOCAL DEVELOPMENT
    volumes:
      - './pgadmin:/pgadmin4-servers:ro' # read-only bind mount for server list
      - 'SetTheory-pgadmin-data:/var/lib/pgadmin' # persistent storage for pgAdmin data

networks:
  settheory_local_network:
    name: settheory_local_network
    external: true
